---
title: "Q&A"

callout-appearance: minimal
---

## Class attendance and enrolment questions

::: {.callout-note collapse="true" appearance="minimal"}
## Can Foundations of Biostatistics course be completed entirely remotely? Are there any attendance requirements?

There is no requirement to attend any in-person event. Many students don't come to campus, and the course is designed to be accessible by all students. In fact, many students have completed the course while living overseas.
:::

::: {.callout-note collapse="true"}
## I've heard the workload 

Bleep
:::


::: {.callout-note collapse="true" appearance="minimal"}
## I can only study one course this term. Should I study Foundations of Biostatistics or Foundations of Epidemiology?

There is no right answer to this question - completing either course first would be fine.

Many students put off studying Foundations of Biostatistics in the (mistaken) belief that it will be too difficult - and then report that they wish they had studied the course earlier. Foundations of Biostatistics is designed to be accessible for all students, regardless of your maths background.

Your future course choices and your timetable might help you answer this. For example, if you know you want to complete Regression Methods in Biostatistics, then completing Foundations of Biostatistics first would be sensible.

There's no "right" course to be completed first. You will get a lot out of either course, whatever you decide to complete first.
:::

::: {.callout-note collapse="true" appearance="minimal"}
## Are there any prerequisites or any expected background knowledge for this course?

No! There are no prerequisite mathematics requirements, and you do not need to have studied statistics before.

If it has been a while since you have studied maths, the following resources from Unit 1 of the Algebra Basics from the Khan Academy might be useful:

[link](https://www.khanacademy.org/math/algebra-basics/basic-alg-foundations)

Don't worry that it's got "algebra" in its title, it's just some basic maths skills that you might not remember so well. And don't feel like you need to formally enrol, or study every section: just watch some of the videos and read some of the notes for the topics that you might not remember - and maybe take some of the quizzes. I would recommend the section on "Order of Operations", but you can definitely skip "Area of triangles" and "Circumference and area of circles" 
:::







## Class attendance and enrolment questions

- I am an external student, can I come to the tutorials?
No, you will need to change your enrolment to internal if you would like to attend the face-to-face tutorial classes. You will need to do this before the end of week 1. However, you are welcome to attend the Monday night Stata clinics as an external student if you live in Sydney. We schedule weekly webinar tutorials for external students.

- I am an external student, can I attend the lectures?
Yes! You can watch our lectures online (Thursdays 6-8pm) via MS Teams, or watch a recording later. If you're keen to come to the lecture in person, feel free to contact me before the session.

- I am an internal student, how do I find which tutorial class I have been allocated to?
We will announce tutorial allocation at the end of Week 1.

## Computing and other course resources FAQs

- Do I need to buy Stata?
Unless you have access to Stata through work or are regularly able to access campus computers, you will need to purchase Stata. You will need it to complete Module Learning Activities and the assessments. Details about how to purchase Stata are in the course outline.

- I have an old version of Stata, can I use it?
​​​​​​Yes. We use Stata/BE (Basic Edition) Version 18 for this course. Older version of Stata down to version 11 will also be suitable for this course.

- Where can I access Stata on campus?
We have secured licenses for Stata on the computer labs in the Wallace Wurth Building G06/07. This is where the residential workshop and Monday night sessions are held. You can gain access anytime there isn’t a class.

- Do I need to buy a calculator?
No. We no longer have an supervised exam for this course and all assessments can be completed using a computer.

- Can I buy a hard-copy of the course notes?
We no longer provide printed copies of our course notes due to low interest. You can download the course notes in PDF for printing.

- Do I need to buy a text book?

You do not need to buy a text book.

All the content you need for this course is provided in the course notes, including instructions for Stata. If you want to supplement the content we provide, recommended readings are provided for each module. You can purchase these books or access them through the UNSW library as an e-book. The links are in the course outline.

- Where can I find a private tutor?
You may contact the course convenors to request a list of potential private tutors. These are PhD students from our School and affiliated research centres. If you do not live in Sydney/can't come on campus, you may organise online sessions with your tutor. Note that payment to private tutors is a private arrangement between you and the tutor - we only provide contact details.  

## Assessment questions

- Where can I find resources related to assessment policies within the School of Population Health?
Link?

- How do I submit a special consideration?
https://sph.med.unsw.edu.au/current-students/student-resources/special-consideration

Due to the nature of the assessments for this course, any late submissions (i.e. after the ideal answers are released) without express permission from course convenors will not be accepted. See the course outline for more details.

- How many assessments are there and where can I find the instructions?

Details about the assessments can be found in the course outline and in the assessment section on the Moodle webpage for your course.

- I heard there is an exam for this course! Is that true?

Previous years have included an exam (on campus or invigilated for external students). We no longer have an exam.

## General questions

- Where can I find recordings for the lectures?

You will be able to access the recordings for lectures and webinars in the Microsoft Teams site.

- How do I change the forum notifications I receive via email?
Please consult the guide to change your forum notification settings here: https://www.student.unsw.edu.au/edit-your-moodle-student-profile

- Where do I find more information about the support available for my Program?

https://sph.med.unsw.edu.au/current-students/student-resources/program-support


Do you have a question that is not answered here? Please [email me](mailto:t.dobbins@unsw.edu.au), and I can provide an answer.
