---
title: "Foundations of Biostatistics"
subtitle: "Term 2, 2026"
---

# Course schedule

+---------+--------------------+----------------------+----------------------------+
| Week    | Lecture            | Online Tutorials\    | Drop-in Software Clinic\   |
|         |                    | jamovi or R          | In-person or online        |
+=========+====================+======================+============================+
| Week 0  | Introductory video |                      | Introductory video         |
+---------+--------------------+----------------------+----------------------------+
| Week 1  | Lecture 1\         | Tutorial 1\          | \                          |
|         | Monday 1 June\     | Thursday 4 June\     | Friday 5 June\             |
|         | 6pm-8pm            | 6pm-8pm              | 10am-12pm                  |
+---------+--------------------+----------------------+----------------------------+
| Week 2  | Lecture 2\         | Tutorial 2\          | \                          |
|         | NSW Holiday\       | Thursday 11 June\    | Friday 12 June\            |
|         | Recorded lecture   | 6pm-8pm              | 10am-12pm                  |
+---------+--------------------+----------------------+----------------------------+
| Week 3  | Lecture 3\         | Tutorial 3\          | \                          |
|         | Monday 15 June\    | Thursday 18 June\    | Friday 19 June\            |
|         | 6pm-8pm            | 6pm-8pm              | 10am-12pm                  |
+---------+--------------------+----------------------+----------------------------+
| Week 4  | Lecture 4\         | Tutorial 4\          | \                          |
|         | Monday 22 June\    | Thursday 25 June\    | Friday 26 June\            |
|         | 6pm-8pm            | 6pm-8pm              | 10am-12pm                  |
+---------+--------------------+----------------------+----------------------------+
| Week 5  | Lecture 5\         | Tutorial 5\          | \                          |
|         | Monday 29 June\    | Thursday 2 July\     | Friday 3 July\             |
|         | 6pm-8pm            | 6pm-8pm              | 10am-12pm                  |
+---------+--------------------+----------------------+----------------------------+
| Week 6  | Lecture 6\         | Tutorial 6\          | \                          |
|         | Monday 6 July\     | Thursday 9 July\     | Friday 10 July\            |
|         | 6pm-8pm            | 6pm-8pm              | 10am-12pm                  |
+---------+--------------------+----------------------+----------------------------+
| Week 7  | Lecture 7\         | Tutorial 7\          | \                          |
|         | Monday 13 July\    | Thursday 16 July\    | Friday 17 July\            |
|         | 6pm-8pm            | 6pm-8pm              | 10am-12pm                  |
+---------+--------------------+----------------------+----------------------------+
| Week 8  | Lecture 8\         | Tutorial 8\          | \                          |
|         | Monday 20 July\    | Thursday 23 July\    | Friday 24 July\            |
|         | 6pm-8pm            | 6pm-8pm              | 10am-12pm                  |
+---------+--------------------+----------------------+----------------------------+
| Week 9  | Lecture 9\         | Tutorial 9\          | \                          |
|         | Monday 27 July\    | Thursday 30 July\    | Friday 31 July\            |
|         | 6pm-8pm            | 6pm-8pm              | 10am-12pm                  |
+---------+--------------------+----------------------+----------------------------+
| Week 10 | Lecture 10\        | Tutorial 10\         | \                          |
|         | Monday 3 August\   | Thursday 6 August\   | Friday 7 August\           |
|         | 6pm-8pm            | 6pm-8pm              | 10am-12pm                  |
+---------+--------------------+----------------------+----------------------------+